import test from 'node:test';
import assert from 'node:assert/strict';
import { DatabaseSync } from 'node:sqlite';
import { AccountStore } from '../lib/accounts.ts';
import { handleAccountRequest } from '../lib/account-http.ts';

const password = 'Test-only-password-9837!';
const input = (email: string) => ({ email, password, displayName: email.split('@')[0] });
test('owner bootstrapping, forced registration role, password hashing, cookie sessions and revocation', async () => {
  const db = new DatabaseSync(':memory:');
  const store = new AccountStore(db);
  assert.equal(store.initialized(), false);
  await assert.rejects(store.register(input('first@example.com')));
  const owner = await store.createOwner(input('owner@example.com'));
  await assert.rejects(store.createOwner(input('owner2@example.com')));
  const user = await store.register({ ...input('user@example.com'), role: 'OWNER', status: 'ACTIVE' });
  assert.equal(user.role, 'USER');
  const row = db.prepare('SELECT passwordHash FROM accounts WHERE id=?').get(user.id) as { passwordHash: string };
  assert.ok(row.passwordHash.startsWith('scrypt-v1$'));
  assert.ok(!row.passwordHash.includes(password));
  const session = await store.login(input('user@example.com'));
  assert.equal(store.session(session.token)?.id, user.id);
  const hashRow = db.prepare('SELECT tokenHash FROM account_sessions').get() as { tokenHash: string };
  assert.notEqual(hashRow.tokenHash, session.token);
  assert.throws(() => store.dashboard(user));
  assert.throws(() => store.update(user, owner.id, 'ADMIN', 'DISABLED'));
  assert.throws(() => store.update(owner, owner.id, 'USER', 'DISABLED'));
  store.update(owner, user.id, 'ADMIN', 'ACTIVE');
  assert.equal(store.session(session.token), null);
  const adminSession = await store.login(input('user@example.com'));
  assert.equal(adminSession.account.role, 'ADMIN');
  const dashboard = store.dashboard(adminSession.account);
  assert.equal(dashboard.total, 2);
  assert.ok(!JSON.stringify(dashboard).includes('passwordHash'));
  assert.throws(() => store.update(adminSession.account, owner.id, 'USER', 'ACTIVE'));
  store.update(owner, user.id, 'ADMIN', 'DISABLED');
  assert.equal(store.session(adminSession.token), null);
  await assert.rejects(store.login(input('user@example.com')));
  const ownerSession = await store.login(input('owner@example.com'));
  store.logout(ownerSession.token);
  assert.equal(store.session(ownerSession.token), null);
  db.close();
});
test('HTTP origin checks, anonymous denial, secure cookie and session expiry', async () => {
  const db = new DatabaseSync(':memory:');
  const store = new AccountStore(db);
  await store.createOwner(input('owner@example.com'));
  const request = (route: string, data?: unknown, origin = 'https://analyst.example') => new Request('https://analyst.example/api/accounts/' + route, data === undefined ? {} : { method: 'POST', headers: { Origin: origin, 'Content-Type': 'application/json' }, body: JSON.stringify(data) });
  assert.equal((await handleAccountRequest(request('admin'), 'admin', store)).status, 401);
  assert.equal((await handleAccountRequest(request('login', input('owner@example.com'), 'https://evil.example'), 'login', store)).status, 403);
  const response = await handleAccountRequest(request('login', input('owner@example.com')), 'login', store);
  assert.equal(response.status, 200);
  const cookie = response.headers.get('Set-Cookie')!;
  assert.match(cookie, /HttpOnly/); assert.match(cookie, /Secure/); assert.match(cookie, /SameSite=Lax/);
  const body = await response.json() as { token?: string };
  assert.equal(body.token, undefined);
  const authenticated = new Request('https://analyst.example/api/accounts/admin', { headers: { Cookie: cookie.split(';')[0] } });
  assert.equal((await handleAccountRequest(authenticated, 'admin', store)).status, 200);
  db.prepare('UPDATE account_sessions SET expiresAt=0').run();
  assert.equal((await handleAccountRequest(authenticated, 'admin', store)).status, 401);
  assert.equal((await handleAccountRequest(request('login', { ...input('owner@example.com'), password: 'wrong-password-123' }), 'login', store)).status, 401);
  assert.equal((await handleAccountRequest(request('login', { ...input('missing@example.com'), password: 'wrong-password-123' }), 'login', store)).status, 401);
  assert.equal((await handleAccountRequest(request('register', { ...input('huge@example.com'), extra: 'x'.repeat(5000) }), 'register', store)).status, 413);
  db.close();
});
test('failed login attempts are limited without depending on spoofable proxy headers', async () => {
  const db = new DatabaseSync(':memory:');
  const store = new AccountStore(db);
  await store.createOwner(input('owner@example.com'));
  for (let i = 0; i < 10; i++) await assert.rejects(store.login({ ...input('owner@example.com'), password: 'incorrect-password-123' }), { status: 401 });
  await assert.rejects(store.login(input('owner@example.com')), { status: 429 });
  db.prepare('UPDATE account_limits SET expiresAt=0').run();
  assert.equal((await store.login(input('owner@example.com'))).account.role, 'OWNER');
  db.close();
});
